name: Deploy Agora

on:
  workflow_dispatch:
    inputs:
      key_vault_id:
        description: "Azure Key Vault ID"
        required: true
        type: string
      secret_name:
        description: "Secret Name"
        required: true
        type: string

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    outputs:
      domain_name: ${{ steps.determine-domain.outputs.domain_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext
          sudo apt-get install -y rsync

      - name: Fetch Azure Function Secrets
        id: fetch-secrets
        run: |
          AZURE_FUNCTION_URL="${{ secrets.AZURE_FUNCTION_URL }}"
          AZURE_FUNCTION_CODE="${{ secrets.AZURE_FUNCTION_CODE }}"
          KEY_VAULT_ID="${{ github.event.inputs.key_vault_id }}"
          SECRET_NAME="${{ github.event.inputs.secret_name }}"

          # Build the Azure Function URL
          URL="$AZURE_FUNCTION_URL?code=$AZURE_FUNCTION_CODE&key_vault_id=$KEY_VAULT_ID&name=$SECRET_NAME"

          SECRETS=$(curl -s -H "Content-Type: application/json" -X GET "$URL")

          if [ -z "$SECRETS" ]; then
              echo "Failed to retrieve secrets from Azure Function."
              exit 1
          fi

          # Remove "Secret value: " from the response
          SECRETS=$(echo "$SECRETS" | sed 's/^Secret value: //')

          # Save the secrets directly to the .env file
          echo "$SECRETS" > .env

          echo "Secrets fetched and saved to .env file."

          GH_ACTIONS_URL="$AZURE_FUNCTION_URL?code=$AZURE_FUNCTION_CODE&key_vault_id=$KEY_VAULT_ID&name=github-actions"

          # Get github-actions secrets
          GH_ACTIONS_SECRETS=$(curl -s -H "Content-Type: application/json" -X GET "$GH_ACTIONS_URL")

          if [ -z "$GH_ACTIONS_SECRETS" ]; then
              echo "Failed to retrieve secrets from Azure Function."
              exit 1
          fi

          # Remove "Secret value: " from the response
          GH_ACTIONS_SECRETS=$(echo "$GH_ACTIONS_SECRETS" | sed 's/^Secret value: //')

          # Save the secrets directly to the .env file
          echo "$GH_ACTIONS_SECRETS" >> .env

      - name: Remove the 'Secret value ' from the .env file
        run: |
          # Remove the 'Secret value: ' from the .env file
          sed -i 's/Secret value: //g' .env

      - name: Generate new .env file from template
        run: |
          # Assume you have .env.template in your repository
          if [ ! -f .env.template ]; then
              echo "Missing .env.template file in the repository."
              exit 1
          fi

          set -a
          source .env
          set +a

          # Generate new .env file by replacing placeholders with actual values
          envsubst < .env.template > .env.generated

      - name: Mask SSH Key
        run: |
          # Fetch the SSH key from input or secrets
          SSH_KEY=$(jq -r '.inputs.ssh_key' $GITHUB_EVENT_PATH)

          # Check if SSH_KEY is not empty
          if [ -n "$SSH_KEY" ]; then
            # Mask the SSH key to prevent it from showing in logs
            echo ::add-mask::$SSH_KEY
            echo ::add-mask::$SSH_USER
            echo ::add-mask::$SSH_HOST

            # Store the SSH key in a GitHub Actions environment variable
            echo SSH_KEY=$SSH_KEY >> $GITHUB_ENV
          else
            echo "No SSH key provided, skipping mask."
          fi

      - name: Source and decode SSH key
        id: source-env
        run: |
          set -a
          source .env
          set +a

          # Create the .ssh directory if it doesn't exist
          mkdir -p ~/.ssh

          # Decode the base64 SSH key and ensure a new line at the end of the private key
          echo "$SSH_KEY" | base64 -d > ~/.ssh/deploy_key_nrd
          chmod 600 ~/.ssh/deploy_key_nrd

          # Extract the public key from the private key
          ssh-keygen -y -f ~/.ssh/deploy_key_nrd > ~/.ssh/deploy_key_nrd.pub

          # Set necessary environment variables using GITHUB_ENV instead of echoing
          echo "SSH_HOST=${AGORA_SSH_HOST}" >> $GITHUB_ENV
          echo "SSH_USER=${AGORA_SSH_USER}" >> $GITHUB_ENV
          echo "DOMAIN_NAME=${AGORA_DOMAIN_NAME}" >> $GITHUB_ENV

      - name: Determine domain name
        id: determine-domain
        run: |
          DOMAIN_NAME=$(echo $DOMAIN_NAME | sed 's/^https:\/\///')
          echo "domain_name=$DOMAIN_NAME" >> $GITHUB_OUTPUT

      - name: Rsync files and node_modules to the server
        run: |
          set -a
          source .env
          set +a

          # Rsync application files
          rsync -avz --no-perms --no-owner --no-group -e "ssh -i ~/.ssh/deploy_key_nrd -o StrictHostKeyChecking=no" \
          --exclude=".git/" --exclude=".github/" --exclude=".env" --exclude=".env.template" --exclude=".env.generated" --exclude=".vscode/" --rsync-path="sudo rsync" \
          ./ $SSH_USER@$SSH_HOST:/var/www/$DOMAIN_NAME

          # Rsync node_modules to the server
          rsync -avz --no-perms --no-owner --no-group -e "ssh -i ~/.ssh/deploy_key_nrd -o StrictHostKeyChecking=no" \
          --rsync-path="sudo rsync" \
          node_modules/ $SSH_USER@$SSH_HOST:/var/www/$DOMAIN_NAME/node_modules/

          # Sync the generated .env file
          rsync -avz --no-perms --no-owner --no-group -e "ssh -i ~/.ssh/deploy_key_nrd -o StrictHostKeyChecking=no" \
          --rsync-path="sudo rsync" \
          .env.generated $SSH_USER@$SSH_HOST:/var/www/$DOMAIN_NAME/.env

      - name: SSH to Azure VM and run deployment commands
        run: |
          ssh -i ~/.ssh/deploy_key_nrd -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            cd /var/www/$DOMAIN_NAME
            sudo chown -R $SSH_USER:www-data .
            sudo chmod -R 755 .

            # Restart or start the app with pm2
            pm2 restart agora-token-app || pm2 start index.js --name agora-token-app
          EOF

  notify:
    name: Send notification
    runs-on: ubuntu-latest
    needs: [deploy-app]
    env:
      DOMAIN_NAME: ${{ needs.deploy-app.outputs.domain_name }}
    steps:
      - name: Notify slack channel
        id: slack-message
        uses: slackapi/slack-github-action@v1.24.0
        if: success()
        with:
          channel-id: ${{ secrets.SLACK_NOTIFICATIONS_CHANNEL }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✅ New service available! "
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Site Domain: `${{ env.DOMAIN_NAME }}`"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Check out the build log"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Visit the changes live"
                      },
                      "url": "https://${{ env.DOMAIN_NAME }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_TOKEN }}
      - name: Notify slack channel on failure
        id: slack-failure-message
        uses: slackapi/slack-github-action@v1.24.0
        if: failure()
        with:
          channel-id: ${{ secrets.SLACK_NOTIFICATIONS_CHANNEL }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "❌ Workflow failed!"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Site Domain: `${{ env.DOMAIN_NAME }}`"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Please check the workflow logs for more details."
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Logs"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_TOKEN }}
